/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.onlinestore.products;

import io.vertx.core.Vertx;

public class ProductServiceApplication {
	
	public static void main(String[] args) {
			
		Vertx vrts = Vertx.vertx();
		vrts.deployVerticle(new ProductServiceTest(3001));
		while(true);
	}
	
}
